/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package student.management.system;

import java.awt.Color;
import java.awt.Point;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static student.management.system.Main.a;
import static student.management.system.Main.cbTheme;
import static student.management.system.Main.color;
import static student.management.system.Main.s;

/**
 *
 * @author Developer
 */
public class login extends javax.swing.JFrame {
    public static String userna;
    boolean sign = true;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        panelSignUp.setVisible(false);
        this.setSize(502 , 300);
        //jLabel9.setVisible(false);
         //   jLabel8.setVisible(false);
         //   cbStream.setVisible(false);
         //   cbSection.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        labelLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelExit = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbTeacher = new javax.swing.JRadioButton();
        rbStudent = new javax.swing.JRadioButton();
        labelLogin = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        checkNewUser = new javax.swing.JCheckBox();
        panelSignUp = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfAge = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfAddress = new javax.swing.JTextArea();
        tfPhone = new javax.swing.JTextField();
        tfSubject = new javax.swing.JTextField();
        cbStream = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbSection = new javax.swing.JComboBox();
        labelRoll = new javax.swing.JLabel();
        tfRoll = new javax.swing.JTextField();
        cbShowPass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        labelLogo.setBackground(new java.awt.Color(255, 0, 0));
        labelLogo.setFont(new java.awt.Font("Terminator Two", 1, 18)); // NOI18N
        labelLogo.setForeground(new java.awt.Color(255, 255, 255));
        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setText("Student Databse Management System");
        labelLogo.setOpaque(true);

        jLabel1.setText("Username");

        labelExit.setBackground(new java.awt.Color(255, 255, 255));
        labelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelExit.setText("Exit");
        labelExit.setOpaque(true);
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelExitMouseReleased(evt);
            }
        });

        jLabel3.setText("Password");

        buttonGroup1.add(rbTeacher);
        rbTeacher.setText("Teacher");
        rbTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbTeacherMouseClicked(evt);
            }
        });

        buttonGroup1.add(rbStudent);
        rbStudent.setText("Student");
        rbStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbStudentMouseClicked(evt);
            }
        });

        labelLogin.setBackground(new java.awt.Color(255, 255, 255));
        labelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogin.setText("Login");
        labelLogin.setOpaque(true);
        labelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelLoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelLoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelLoginMouseReleased(evt);
            }
        });

        checkNewUser.setText("New User?");
        checkNewUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkNewUserMouseClicked(evt);
            }
        });

        panelSignUp.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Name");

        jLabel4.setText("Age");

        jLabel5.setText("Address");

        jLabel6.setText("Phone Number");

        jLabel7.setText("Subject");

        tfAddress.setColumns(20);
        tfAddress.setLineWrap(true);
        tfAddress.setRows(5);
        tfAddress.setWrapStyleWord(true);
        jScrollPane1.setViewportView(tfAddress);

        cbStream.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbStreamItemStateChanged(evt);
            }
        });

        jLabel8.setText("Stream");

        jLabel9.setText("Section");

        labelRoll.setText("Roll No");

        javax.swing.GroupLayout panelSignUpLayout = new javax.swing.GroupLayout(panelSignUp);
        panelSignUp.setLayout(panelSignUpLayout);
        panelSignUpLayout.setHorizontalGroup(
            panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignUpLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSignUpLayout.createSequentialGroup()
                        .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7))
                            .addGroup(panelSignUpLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbStream, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfSubject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelSignUpLayout.createSequentialGroup()
                                .addComponent(cbSection, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelRoll)
                                .addGap(14, 14, 14))))
                    .addGroup(panelSignUpLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSignUpLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(tfRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        panelSignUpLayout.setVerticalGroup(
            panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRoll)
                    .addComponent(tfRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        cbShowPass.setText("Show Pass");
        cbShowPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbShowPassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelLogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkNewUser)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfUsername, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbTeacher)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                        .addComponent(rbStudent))
                                    .addComponent(tfPassword, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbShowPass))))
                    .addComponent(panelSignUp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbShowPass))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbStudent)
                    .addComponent(rbTeacher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkNewUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelExitMouseClicked

    public static String md5Java(String pass) {
        String digest = null;

        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] hash = md.digest(pass.getBytes("UTF-8"));
            StringBuilder sb = new StringBuilder(2 * hash.length);
            for (byte b : hash) {
                sb.append(String.format("%02x", b & 0xff));
            }
            digest = sb.toString();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return digest;
    }
    
    void login(){
        
        String password, encryptedPassword;
        boolean login = false;
        ResultSet rs = null;
        char[] pass = tfPassword.getPassword();
        password = new String(pass);
        userna = tfUsername.getText();
        encryptedPassword = md5Java(password);
        String category = null;
        //System.out.println(encryptedPassword);
        
        if(rbStudent.isSelected()){
            category="S";
        }
        else if(rbTeacher.isSelected()){
            category="T";
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a category.");
            return;
        }
        
        

        String query = "select * from login;";
        //Preparing Database Connection
        Connection con = helpers.DBHelper.getConnection();
        Statement stmt = helpers.DBHelper.getStatement(con);
        try {
            rs = stmt.executeQuery(query);

            while (rs.next()) {
                if (userna.equals(rs.getString("username"))) {
                    if (encryptedPassword.equals(rs.getString("password"))) {
                        if(category.equals(rs.getString("category"))){
                            login = true;
                        }
                    }
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        if (login == true) {
            Main main = new Main();
            main.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "UserName or Password incorrect. Please try again...");
        }
        
        String user = userna;
        ResultSet rsk;
        int index = 0;
        String query50 = "select color from colorchoice where username ='" + userna + "';";
        
            try {
                rsk = s.executeQuery(query50);
                while (rsk.next()) {
                    color = rsk.getString("color");
                    //System.out.println(rsk.getString("color"));
                    if (color.equals("red") || color.equals("Red") || color.equals("RED")) {
                        a = Color.red;
                        index=0;
                        //helpers.DesignHelper.themeChange();
                    } else if (color.equals("blue") || color.equals("Blue") || color.equals("BLUE")) {
                        a = Color.BLUE;
                        index=1;
                        //helpers.DesignHelper.themeChange();
                    } else if (color.equals("cyan") || color.equals("Cyan") || color.equals("CYAN")) {
                        a = Color.CYAN;
                        index=2;
                        //helpers.DesignHelper.themeChange();
                    } else if (color.equals("green") || color.equals("Green") || color.equals("GREEN")) {
                        a = Color.GREEN;
                        index=4;
                        //helpers.DesignHelper.themeChange();
                    } else if (color.equals("gray")|| color.equals("Gray") || color.equals("GRAY")) {
                        a = Color.GRAY;
                        index=3;
                        //helpers.DesignHelper.themeChange();
                    } else if (color.equals("yellow") || color.equals("Yellow") || color.equals("YELLOW")) {
                        a = Color.YELLOW;
                        index=8;
                        //helpers.DesignHelper.themeChange();
                    } else if (color.equals("magenta") || color.equals("Magenta") || color.equals("MAGENTA")) {
                        a = Color.MAGENTA;
                        index=5;
                        //helpers.DesignHelper.themeChange();
                    } else if (color.equals("orange") || color.equals("Orange") || color.equals("ORANGE")) {
                        a = Color.ORANGE;
                        index=6;
                        //helpers.DesignHelper.themeChange();
                    } else if (color.equals("pink") || color.equals("Pink") || color.equals("PINK")) {
                        a = Color.PINK;
                        index=7;
                        //helpers.DesignHelper.themeChange();
                    } else {
                        a = Color.red;
                        //helpers.DesignHelper.themeChange();
                    }
                    
                    //themeChange();
                }
                rsk.close();
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, "Error");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error");
            }
            
            cbTheme.setSelectedIndex(index);
            //System.out.println("SelectedItem for cb in login() : " + cbTheme.getSelectedItem() + " Index: " + index);
            
        
    }
    
    void getStreams(){
        Vector<String> s = new Vector<>();
        Connection con = helpers.DBHelper.getConnection();
        String query = "select distinct stream from sections_list order by stream;";
        PreparedStatement stmt = helpers.DBHelper.getPreparedStatement(con, query);
        try {
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                s.add(rs.getString("stream"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Request could not be completed due to an error.\nPlease contact administrator for more details.");
        }
        DefaultComboBoxModel jcbModel;
        jcbModel = new DefaultComboBoxModel(s);
        cbStream.setModel(jcbModel);
        
    }
    public static String stream=null;
    void getSections(){
        
        int a = cbStream.getSelectedIndex();
        if(a==0){
            stream = "Commerce";
        }
        else if(a==1){
            stream = "Humanities";
        }
        else if(a==2){
            stream = "Science";
        }
         Vector<String> s = new Vector<>();
        Connection con = helpers.DBHelper.getConnection();
        String queryy = "select distinct section from sections_list where stream='"+stream+"';";
        Statement stmt = helpers.DBHelper.getStatement(con);
        
            ResultSet rs=null;
        try {
            rs = stmt.executeQuery(queryy);
            while (rs.next()) {
                s.add(rs.getString("section"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        DefaultComboBoxModel jcbModel;
        jcbModel = new DefaultComboBoxModel(s);
        cbSection.setModel(jcbModel);
    }
    
    void signup(){
        if(rbTeacher.isSelected()){
            
        try {
            String username, pass, name, address, phone, subject;
            int age;
            
            String encryptedPass;
            
            
            char[] passw = tfPassword.getPassword();
            pass = new String(passw);
            username = tfUsername.getText();
            encryptedPass = md5Java(pass);
            
            name = tfName.getText();
            address = tfAddress.getText();
            phone = tfPhone.getText();
            subject = tfSubject.getText();
            try{
            age = Integer.parseInt(tfAge.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Please enter the age...");
                sign = false;
                age = 0;
            }
            String query1 = "insert into login values('"+username+"', '"+encryptedPass+"', 'T');";
            String query2 = "insert into teachers_details values('"+username+"', '" +name+ "', "+age+", '" + address + "', '"+phone+"', '"+ subject+"');";
            Connection con = helpers.DBHelper.getConnection();
            PreparedStatement stmt = helpers.DBHelper.getPreparedStatement(con, query1);
            try {
                stmt.execute(query1);
            } catch (SQLException ex) {
                //Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
            PreparedStatement stmt2 = helpers.DBHelper.getPreparedStatement(con, query2);
            stmt2.execute(query2);
        } catch (SQLException ex) {
            //Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        else if(rbStudent.isSelected()){
            
            try {
                String username, password, encryptedPassword, name, address, phone, vclass, section;
                int age;
                int rollno;
                try{
                rollno = Integer.parseInt(tfRoll.getText());
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Please enter the RollNo...");
                    rollno = -1;
                }
                
                username = tfUsername.getText();
                char[] passw = tfPassword.getPassword();
                password = new String(passw);
                encryptedPassword = md5Java(password);
                try{
            age = Integer.parseInt(tfAge.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Please enter the age...");
                sign = false;
                age = 0;
            }
                name = tfName.getText();
                address = tfAddress.getText();
                phone = tfPhone.getText();
                vclass = tfSubject.getText();
                section = (String)cbSection.getSelectedItem();
                String query1 = "insert into login values('"+username+"', '"+encryptedPassword+"', 'S');";
                Connection con = helpers.DBHelper.getConnection();
                String query2 = "insert into students_details values('"+username+"', '"+name+"', "+age+", '"+address+"', '"+phone+"', '"+vclass+"', '"+section+"', "+rollno+");";
                PreparedStatement stmt1 = helpers.DBHelper.getPreparedStatement(con, query1);
                try {
                    stmt1.execute(query1);
                } catch (SQLException ex) {
                    //Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
                PreparedStatement stmt2 = helpers.DBHelper.getPreparedStatement(con, query2);
                stmt2.execute(query2);
                
            } catch (SQLException ex) {
               // Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }
    
    private void labelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginMouseClicked
        helpers.DesignHelper.button_Pressed(labelLogin);
        if(checkNewUser.isSelected()==false){
        login();
        //Main main = new Main();
         //   main.setVisible(true);
           // this.setVisible(false);
        }
        if(checkNewUser.isSelected()){
            signup();
            if(sign)
            JOptionPane.showMessageDialog(null,"Sign Up Successful.");
            else
                return;
            
            login main = new login();
            main.setVisible(true);
            this.setVisible(false);
            
        }
    }//GEN-LAST:event_labelLoginMouseClicked

    private void labelLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginMouseEntered
        helpers.DesignHelper.button_Entered(labelLogin);
    }//GEN-LAST:event_labelLoginMouseEntered

    private void labelLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginMouseExited
        helpers.DesignHelper.button_Exited(labelLogin);
    }//GEN-LAST:event_labelLoginMouseExited

    private void labelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseEntered
        helpers.DesignHelper.button_Entered(labelExit);
    }//GEN-LAST:event_labelExitMouseEntered

    private void labelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseExited
        helpers.DesignHelper.button_Exited(labelExit);
    }//GEN-LAST:event_labelExitMouseExited

    private void labelLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginMousePressed
        helpers.DesignHelper.button_Pressed(labelLogin);
    }//GEN-LAST:event_labelLoginMousePressed

    private void labelLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginMouseReleased
        helpers.DesignHelper.button_Released(labelLogin);
    }//GEN-LAST:event_labelLoginMouseReleased

    private void labelExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMousePressed
        helpers.DesignHelper.button_Pressed(labelExit);
    }//GEN-LAST:event_labelExitMousePressed

    private void labelExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseReleased
        helpers.DesignHelper.button_Released(labelExit);
                
    }//GEN-LAST:event_labelExitMouseReleased

    private void checkNewUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkNewUserMouseClicked
        if(rbTeacher.isSelected()==false && rbStudent.isSelected()==false){
            JOptionPane.showMessageDialog(null,"Please tell us if you are a teacher or a student before you proceed for signup.");
            checkNewUser.setSelected(false);
            return;
        }
        if(checkNewUser.isSelected()){
            
            panelSignUp.setSize(502, 250);
            panelSignUp.setVisible(true);
            labelLogin.setText("Sign Up");
            if(rbTeacher.isSelected()){
                this.setSize(502, 580);
                panelSignUp.setSize(502, 250);
                jLabel9.setVisible(false);
                labelRoll.setVisible(false);
            tfRoll.setVisible(false);
            jLabel8.setVisible(false);
            cbStream.setVisible(false);
            cbSection.setVisible(false);
            jLabel7.setText("Subject");
            }
            if(rbStudent.isSelected()){
                 this.setSize(502, 648);
                 panelSignUp.setSize(502, 312);
                 jLabel9.setVisible(true);
            jLabel8.setVisible(true);
            cbStream.setVisible(true);
            cbSection.setVisible(true);
            labelRoll.setVisible(true);
            tfRoll.setVisible(true);
            jLabel7.setText("Class");
            getStreams();
            getSections();
            }
            
        }
        else if(checkNewUser.isSelected()==false){
            this.setSize(502, 300);
            panelSignUp.setVisible(false);
            labelLogin.setText("Login");
        }
        
    }//GEN-LAST:event_checkNewUserMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void rbTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbTeacherMouseClicked
        if(checkNewUser.isSelected()){
            
                this.setSize(502, 580);
                //panelSignUp.setSize(502, 250);
            jLabel9.setVisible(false);
            jLabel8.setVisible(false);
            cbStream.setVisible(false);
            cbSection.setVisible(false);
            labelRoll.setVisible(false);
            tfRoll.setVisible(false);
            jLabel7.setText("Subject");
        }
    }//GEN-LAST:event_rbTeacherMouseClicked

    private void rbStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbStudentMouseClicked
       if(checkNewUser.isSelected()){
          
                this.setSize(502, 648);
                 panelSignUp.setSize(502, 312);
                jLabel9.setVisible(true);
            jLabel8.setVisible(true);
            labelRoll.setVisible(true);
            tfRoll.setVisible(true);
            cbStream.setVisible(true);
            cbSection.setVisible(true);
            jLabel7.setText("Class");
            getStreams();
            getSections();
       }
    }//GEN-LAST:event_rbStudentMouseClicked

    private void cbStreamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbStreamItemStateChanged
        
        int a = cbStream.getSelectedIndex();
        if(a==0){
            stream = "Commerce";
        }
        else if(a==1){
            stream = "Humanities";
        }
        else if(a==2){
            stream = "Science";
        }
        getSections();
    }//GEN-LAST:event_cbStreamItemStateChanged

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
         Point frameLocation = this.getLocationOnScreen();
        Point drag = evt.getPoint();
        int zx,zy;
        zx=drag.x;
        zy=drag.y;
        int px,py,pa,pb;
        px=frameLocation.x;
        py=frameLocation.y;
        pa=inFrameLocation.x;
        pb=inFrameLocation.y;
        this.setLocation((zx+px)-pa,(zy+py)-pb);
    }//GEN-LAST:event_formMouseDragged
Point inFrameLocation;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        inFrameLocation = evt.getPoint();
    }//GEN-LAST:event_formMousePressed

    private void cbShowPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbShowPassMouseClicked
        if(cbShowPass.isSelected()==true){
            tfPassword.setEchoChar((char)0);
            char a = tfPassword.getEchoChar();
           
            System.out.println(a);
        }
        if(cbShowPass.isSelected()==false){
            tfPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_cbShowPassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbSection;
    private javax.swing.JCheckBox cbShowPass;
    private javax.swing.JComboBox cbStream;
    private javax.swing.JCheckBox checkNewUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelExit;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelRoll;
    private javax.swing.JPanel panelSignUp;
    private javax.swing.JRadioButton rbStudent;
    private javax.swing.JRadioButton rbTeacher;
    private javax.swing.JTextArea tfAddress;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfName;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfRoll;
    private javax.swing.JTextField tfSubject;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
